"""Circularity protocol (PROJECT_SPEC.md, MANDATORY) orchestration.

Step 1: train on config A, test on B and C -- handled by evaluate.py's
  per-config metrics_config_<X>.json outputs; this script assembles them
  into one combined results/metrics_circularity.json.
Step 2: rule-only baseline results alongside model results -- already
  included in each evaluate_config() call (see baselines.py rule_only_baseline).
Step 3: label noise / delayed label robustness -- the simulator already
  injects label_noise per simulator/configs/{A,B,C}.yaml (false_negative_rate,
  false_positive_rate, label_delay_days differ per config: A=5%/2%, B=8%/2%,
  C=10%/4%). We treat configs B and C's degraded metrics (vs A) as the noise
  robustness datapoint, since the simulator's noise knob is baked into config
  generation rather than exposed as a separate re-runnable parameter. This is
  one honest datapoint per config, as PROJECT_SPEC.md allows for a thin slice.
Step 4: real-data vs simulated-data separation -- NOT this agent's job (the
  Benchmark agent owns real-data checks). Every number in this file is
  labeled "on simulated data" so no numbers get blended.
Step 5: realism-gap statement -- written here plainly, no overclaiming.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
RESULTS_DIR = REPO_ROOT / "results"

REALISM_GAP_STATEMENT = (
    "All metrics in this file are computed EXCLUSIVELY on simulator-generated data "
    "(simulator/configs/A.yaml, B.yaml, C.yaml) -- a seeded, rules-based generator "
    "calibrated against public NCRP/RBI/OSM summary statistics, not real bank "
    "transaction data. The simulator's mule-detection 'signal' (e.g. terminal "
    "proximity to recent activity, complaint density) is generated by the SAME "
    "family of heuristics the model is trying to learn (see "
    "simulator/configs/*.yaml terminal_choice rules), which inflates apparent "
    "model performance relative to a real deployment: a real adversary does not "
    "follow a known, stationary terminal_choice distribution, and real background "
    "traffic is not drawn from the same lognormal/poisson generators the model's "
    "features are tuned against. Cross-config generalization (A -> B, A -> C) is "
    "the best available proxy we have for this gap on a thin-slice prototype, but "
    "it is NOT a substitute for real-data validation (see the Benchmark agent's "
    "separate, real-data-only results for AMLworld/Elliptic/Chicago Crimes "
    "sanity checks, reported separately and never blended with these numbers). "
    "Precision@10 and lift figures here should be read as 'does the model learn "
    "the intended mule-activity signal at all', not as an estimate of real-world "
    "fraud-detection performance."
)


def assemble():
    per_config = {}
    for c in ["A", "B", "C"]:
        p = RESULTS_DIR / f"metrics_config_{c}.json"
        if p.exists():
            per_config[c] = json.loads(p.read_text())

    missing = [c for c in ["A", "B", "C"] if c not in per_config]

    combined = {
        "protocol": "circularity protocol per PROJECT_SPEC.md",
        "label": "ALL NUMBERS ON SIMULATED DATA",
        "step1_cross_config_generalization": {
            "trained_on": "A",
            "tested_on": list(per_config.keys()),
            "results_by_config": per_config,
            "missing_configs": missing,
            "complete": len(missing) == 0,
            "note": (
                "Incomplete: configs " + ", ".join(missing) + " were not available when this "
                "was run; circularity protocol step 1 is PARTIAL pending those configs."
                if missing else
                "Complete: model trained on config A evaluated on A (in-sample test split), "
                "B and C (cross-config, different mule topology/timing per PROJECT_SPEC.md)."
            ),
        },
        "step2_rule_only_baseline": {
            "note": (
                "Included inline in each config's 'rule_only' block above. Rule mirrors "
                "the generator's own terminal_choice heuristic per config: A=nearest_to_"
                "last_hop (proximity-based score), B=hotspot_avoidant (inverse recent-"
                "activity score), C=random_in_city (uniform score, no informative signal "
                "by construction -- see simulator/configs/{A,B,C}.yaml and "
                "model/baselines.py:rule_only_baseline for the exact per-config logic)."
            ),
        },
        "step3_label_noise_robustness": {
            "note": (
                "Simulator bakes differing label-noise rates into each config rather than "
                "exposing a standalone re-runnable noise knob (see simulator/configs/*.yaml "
                "label_noise blocks): A: false_negative_rate=0.05, false_positive_rate=0.02, "
                "label_delay_days in [0,14]. B: false_negative_rate=0.08, "
                "false_positive_rate=0.02, label_delay_days in [0,21]. C: "
                "false_negative_rate=0.10, false_positive_rate=0.04, label_delay_days in "
                "[0,10]. We report the model's metric degradation from A (lowest noise) to "
                "B and C (higher noise) as the robustness datapoint -- see "
                "step1_cross_config_generalization.results_by_config for the precision@10 "
                "values to compare directly. This conflates topology/timing shift with "
                "noise-rate shift (both change per config simultaneously), which is a real "
                "limitation of this thin slice: we cannot isolate 'noise effect alone' "
                "without a dedicated same-topology/different-noise config, which was out of "
                "scope for the prototype."
            ),
        },
        "step4_real_data_separation": {
            "note": (
                "Out of scope for the Model agent -- owned by the Benchmark agent "
                "(model/benchmarks/, results/). This file and every metrics_config_*.json "
                "produced by the Model agent are exclusively simulated-data results and are "
                "never blended with any real-data benchmark numbers."
            ),
        },
        "step5_realism_gap_statement": REALISM_GAP_STATEMENT,
    }

    out_path = RESULTS_DIR / "metrics_circularity.json"
    with open(out_path, "w") as f:
        json.dump(combined, f, indent=2, default=str)
    print(f"[circularity] wrote {out_path}")
    print(f"[circularity] complete: {combined['step1_cross_config_generalization']['complete']}")
    if missing:
        print(f"[circularity] MISSING configs: {missing} -- protocol step 1 incomplete, documented in output JSON.")
    return combined


if __name__ == "__main__":
    assemble()
